name: Browser Client Lint Check

on: [pull_request]

jobs:
  browser_client_lint:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install
      run: |
        cd browser-client
        npm install
    - name: Run Lint
      run: |
        cd browser-client
        npm run lint
