name: deploy

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install package dependencies
        working-directory: packages/webc
        run: |
          npm install
      - name: Install Firebase tools
        run: |
          sudo npm install -g firebase-tools
      - name: Build with Webpack
        working-directory: packages/webc
        run: |
          npm run build
      - name: Deploy
        run: |
          npm run use-env -- default --token "${{ secrets.FIREBASE_TOKEN }}"
          npm run deploy -- --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
