name: deploy

on:
  push:
    tags:
      - webc-**

concurrency:
  group: deploy-webc
  cancel-in-progress: true

jobs:
  deploy_site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install package dependencies
        working-directory: packages/webc
        run: |
          npm install
      - name: Install Firebase tools
        run: |
          sudo npm install -g firebase-tools
      - name: Build with Webpack
        working-directory: packages/webc
        run: |
          npm run build
      - name: Set Env
        run: |
          npm run use-env -- default --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Deploy
        working-directory: packages/webc
        run: |
          npm run deploy -- --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive
