name: E2E Preflight Check

on: [pull_request]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Npm Install
        run: |
          npm install
          npm install -g firebase-tools
      - name: Host server
        run: |
          npx firebase serve --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive &
      - name: Run tests
        working-directory: test/e2e
        env:
          HEADLESS: true
        run: |
          npx codeceptjs run