name: preflight

on: [pull_request]

jobs:
  e2e_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Npm Install
        run: |
          npm install
          npm install -g firebase-tools
      - name: Switch to staging
        run: |
          npx firebase use staging --token "${{ secrets.STAGING_FIREBASE_TOKEN }}"
      - name: Host server
        run: |
          npx firebase serve --token "${{ secrets.STAGING_FIREBASE_TOKEN }}" --non-interactive &
      - name: Run tests
        working-directory: test/e2e
        env:
          HEADLESS: true
          LANFLIX_USERNAME: ${{ secrets.STAGING_USERNAME }}
          LANFLIX_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
        run: |
          npx codeceptjs run --verbose --steps