name: Jest Check

on: [pull_request]

jobs:
  jest_check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install
      run: |
        npm install
    - name: Run Jest Tests
      uses: landon-martin/code-coverage-commenter@v0.0.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        coverage-command: "npm run coverage"
        comment-title: "Source Unit Test Coverage Report"
