name: PR Labeler

on:
  pull_request:
    branches: [develop]

jobs:
  label:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v4
