name: PR Labeler

on:
  pull_request:
    branches: [develop]

jobs:
  label:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
