name: Version Bumper

on:
  push:
    branches:
      - develop

jobs: 
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            notifier:
              - .github/workflows/version_bumper.yml
              - packages/notifier/**
            webc:
              - .github/workflows/version_bumper.yml
              - packages/webc/**
      - name: Bump Notifier
        if: steps.changes.outputs.notifier == 'true'
        working-directory: packages/notifier
        run: |
          npm version patch
      - name: Bump Webc
        if: steps.changes.outputs.webc == 'true'
        working-directory: packages/webc
        run: |
          npm version patch
      - name: Checkin
        env:
          PACKAGES: ${{ steps.changes.outputs.changes }}
        run: |
          git add -A
          git commit -m "Bump version: ${PACKAGES}"
          git push && git push --tags
