name: Version Bumper

on:
  push:
    branches:
      - develop

env:
  ACTOR: "GitHub Actions Bot"

jobs: 
  bump:
    runs-on: ubuntu-latest
    if: github.event.head_commit.committer.name != 'GitHub Actions Bot'
    permissions:
      contents: write
    steps:
      - name: GitHub Context
        env:
          CONTEXT: ${{ toJSON(github)}}
        run: 
          echo "${CONTEXT}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_PAT }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            notifier:
              - packages/notifier/**
            webc:
              - packages/webc/**
      - name: Bump Notifier
        if: steps.changes.outputs.notifier == 'true'
        working-directory: packages/notifier
        run: |
          npm version patch
      - name: Bump Webc
        if: steps.changes.outputs.webc == 'true'
        working-directory: packages/webc
        run: |
          npm version patch
      - name: Checkin
        env:
          PACKAGES: ${{ steps.changes.outputs.changes }}
        run: |
          git --version
          git config user.name "${{ env.ACTOR }}"
          git config user.email "<>"
          git add -A
          git commit -m 'Bump version: ${{ env.PACKAGES }}'
          git push -f
